### ISSUE TITLE
OpenShift/Kubernetes Secret support

### ISSUE THREAD

**Issue by benformosa** [envris/tomcat-jdbc#12]
Add support for OpenShift secrets.

A secret named "resource" would contain the username, password and possibly connection string for that resource.

e.g. the secret mydb defined with:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: mydb
data: 
  username: c2NvdHQ=
  password: dGlnZXI=
  url: amRiYzpvcmFjbGU6dGhpbjpAbXlob3N0OjE1MjE6b3JjbA==
```

Gives the following files:

| file | content |
|----|-----------|
| `/var/secret/mydb/username` | `scott` |
| `/var/secret/mydb/password` | `tiger` |
| `/var/secret/mydb/url` | `jdbc:oracle:thin:@myhost:1521:orcl` |

Refer to:
https://docs.openshift.com/container-platform/latest/dev_guide/secrets.html
https://kubernetes.io/docs/concepts/configuration/secret/
