### ISSUE TITLE
Perl Errors

### ISSUE THREAD

**Issue by paulunlmtd** [envris/tomcat-jdbc#16]
When I bring up my app in docker-compose,  I am getting the following errors as it gets stuck in a reboot loop:
`mytcapp   | BEGIN failed--compilation aborted at /usr/local/bin/TomcatContextUtil.pm line 143.
mytcapp   | Compilation failed in require at /usr/local/bin/tomcat-users.pl line 88.
mytcapp   | BEGIN failed--compilation aborted at /usr/local/bin/tomcat-users.pl line 88.
mytcapp   | Can't locate File/Spec/Functions.pm in @INC (you may need to install the File::Spec::Functions module) (@INC contains: /usr/local/bin /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /usr/local/bin/TomcatContextUtil.pm line 143.
`
Here is the compose file I am using:
```
version: '3.1'
services:
  tomcat:
    image: mytcapp:latest
    container_name: mytcapp
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      mytcappDB_RESOURCE: "mytcappDB"
      mytcappDB_USER: "tcuser"
      mytcappDB_HOST: "mssql"
      mytcappDB_PORT: "1433"
      mytcappDB_NAME: "mytcappDB"
      mytcappDB_MAXACTIVE: "5000"
      TOMCAT_ADMIN: "tomcat"
      PARAM_mytcapp.home_NAME: "mytcapp.home"
      PARAM_mytcapp.home_VALUE: "/srv/web/mytcapp"
    secrets:
      - mytcapp_pass
      - tomcat_pass
    networks:
      - proxy-tier
    restart: always
secrets:
  mytcapp_pass:
    file: mytcapp_pass
  tomcat_pass:
    file: tomcat_pass
networks:
  proxy-tier:
    external:
      name: nginx-proxy
```
