### ISSUE TITLE
Support Parameters

### ISSUE THREAD

**Issue by benformosa** [envris/tomcat-jdbc#2]
Support adding parameters to the context.xml with environment variables

E.g.
```yaml
environment:
    PARAM_companyName: "My Company, Incorporated"
    PARAM_companyName_DESCRIPTION: "Name of the company"
    PARAM_companyName_OVERRIDE: "false"
```
or
```yaml
environment:
    PARAM_CMPYNAME_NAME: "companyName"
    PARAM_CMPYNAME_VALUE: "My Company, Incorporated"
    PARAM_CMPYNAME_DESCRIPTION: "Name of the company"
    PARAM_CMPYNAME_OVERRIDE: "false"
```

could yield:
```xml
<Context path="/abc">
...
<Parameter name="companyName"
    description="Name of the company"
    value="My Company, Incorporated"
    override="false"
/>
...
</Context>
```
